<?php

return [
    'language' => 'اللغة', 'english' => 'English', 'bangla' => 'বাংলা', 'arabic' => 'العربية',
    'dashboard' => 'لوحة التحكم', 'manage_user' => 'إدارة المستخدمين', 'view_user' => 'عرض المستخدمين', 'add_user' => 'إضافة مستخدم',
    'manage_profile' => 'إدارة الملف الشخصي', 'your_profile' => 'ملفك الشخصي', 'change_password' => 'تغيير كلمة المرور',
    'academic_setup' => 'الإعداد الأكاديمي', 'student_class' => 'صف الطالب', 'student_year' => 'العام الدراسي', 'student_group' => 'مجموعة الطلاب', 'student_shift' => 'وردية الطلاب',
    'fee_category' => 'فئة الرسوم', 'fee_amount' => 'مبلغ الرسوم حسب الفئة', 'exam_type' => 'نوع الاختبار', 'school_subject' => 'المادة الدراسية', 'assign_subject' => 'تعيين المادة', 'class_routine' => 'جدول الحصص', 'designation' => 'المسمى الوظيفي',
    'student_management' => 'إدارة الطلاب', 'student_registration' => 'تسجيل الطلاب', 'roll_generate' => 'إنشاء الرقم', 'student_attendance' => 'حضور الطلاب', 'registration_fee' => 'رسوم التسجيل', 'monthly_fee' => 'الرسوم الشهرية', 'exam_fee' => 'رسوم الاختبار',
    'employee_management' => 'إدارة الموظفين', 'employee_registration' => 'تسجيل الموظفين', 'employee_salary' => 'راتب الموظف', 'employee_leave' => 'إجازة الموظف', 'employee_attendance' => 'حضور الموظفين', 'employee_monthly_salary' => 'الراتب الشهري للموظف',
    'marks_management' => 'إدارة الدرجات', 'marks_entry' => 'إدخال الدرجات', 'marks_edit' => 'تعديل الدرجات', 'marks_grade' => 'تقدير الدرجات',
    'exam_management' => 'إدارة الاختبارات', 'exam_routine' => 'جدول الاختبارات', 'admit_card' => 'بطاقة الدخول', 'seat_plan' => 'خطة المقاعد',
    'accounts_management' => 'إدارة الحسابات', 'student_fee' => 'رسوم الطلاب', 'other_cost' => 'تكاليف أخرى', 'online_class' => 'الفصل الافتراضي', 'all_classes' => 'كل الفصول', 'create_class' => 'إنشاء فصل', 'class_recordings' => 'تسجيلات الفصول',
    'report_interface' => 'التقارير', 'reports_management' => 'إدارة التقارير', 'monthly_yearly_profit' => 'الربح الشهري والسنوي', 'marksheet_generate' => 'إنشاء كشف الدرجات', 'employee_attendance_report' => 'تقرير حضور الموظفين', 'student_attendance_report' => 'تقرير حضور الطلاب', 'student_result' => 'نتيجة الطالب', 'student_id_card' => 'بطاقة هوية الطالب',
    'notifications' => 'الإشعارات', 'clear_all' => 'مسح الكل', 'view_all' => 'عرض الكل', 'profile' => 'الملف الشخصي', 'my_wallet' => 'محفظتي', 'settings' => 'الإعدادات', 'logout' => 'تسجيل الخروج', 'fullscreen' => 'ملء الشاشة',
    'delete_confirm_title' => 'هل أنت متأكد؟', 'delete_confirm_text' => 'حذف هذه البيانات؟', 'delete_confirm_button' => 'نعم، احذفها!',
    'generate_seat_plan_title' => 'إنشاء خطة المقاعد؟', 'generate_seat_plan_text' => 'سيتم إنشاء ترتيب المقاعد لجميع الطلاب', 'generate_seat_plan_button' => 'نعم، أنشئها!',
    'total_student' => 'إجمالي الطلاب', 'total_present' => 'إجمالي الحضور', 'total_income' => 'إجمالي الدخل', 'total_expense' => 'إجمالي المصروفات', 'monthly_income' => 'دخل هذا الشهر', 'monthly_expense' => 'مصروفات هذا الشهر', 'income_expense_overview' => 'ملخص الدخل والمصروفات', 'students_by_class' => 'الطلاب حسب الصف', 'attendance_last_seven_days' => 'الحضور خلال آخر 7 أيام', 'today_attendance' => 'حضور اليوم', 'income' => 'الدخل', 'expense' => 'المصروفات', 'present' => 'حاضر', 'absent' => 'غائب', 'attendance_rate' => 'نسبة الحضور', 'fee_due_students' => 'الطلاب المتأخرون في الرسوم', 'exam_average' => 'متوسط الدرجات', 'pass_rate' => 'نسبة النجاح', 'quick_actions' => 'إجراءات سريعة', 'add_student' => 'إضافة طالب', 'take_attendance' => 'تسجيل الحضور', 'collect_fee' => 'تحصيل الرسوم', 'enter_marks' => 'إدخال الدرجات', 'upcoming_exams' => 'الاختبارات القادمة', 'date' => 'التاريخ', 'exam' => 'الاختبار', 'class' => 'الصف', 'subject' => 'المادة', 'no_upcoming_exams' => 'لا توجد اختبارات قادمة', 'fee_due_summary' => 'ملخص الرسوم المستحقة', 'students_without_monthly_payment' => 'طلاب لم يدفعوا هذا الشهر', 'estimated_due' => 'المبلغ المستحق تقديرياً', 'open_fee_management' => 'فتح إدارة الرسوم', 'portal' => 'بوابة التواصل', 'communication_portal' => 'بوابة التواصل', 'communication_portal_help' => 'اطرح الأسئلة وتواصل مع مؤسستك.', 'my_conversations' => 'محادثاتي', 'ask_question' => 'طرح سؤال', 'recipient' => 'المستلم', 'choose_recipient' => 'اختر المستلم', 'message' => 'الرسالة', 'send_question' => 'إرسال السؤال', 'send_reply' => 'إرسال الرد', 'write_reply' => 'اكتب ردك...', 'cancel' => 'إلغاء', 'close_conversation' => 'إغلاق المحادثة', 'question_sent' => 'تم إرسال السؤال بنجاح.', 'reply_sent' => 'تم إرسال الرد بنجاح.', 'conversation_closed' => 'تم إغلاق المحادثة.', 'no_conversations' => 'لا توجد محادثات بعد', 'start_question_help' => 'ابدأ محادثة مع معلم أو طالب أو ولي أمر أو موظف.', 'unread' => 'غير مقروء', 'with' => 'مع', 'member' => 'عضو', 'open' => 'مفتوحة', 'closed' => 'مغلقة', 'assignments' => 'الواجبات', 'all_assignments' => 'كل الواجبات', 'create_assignment' => 'إنشاء واجب', 'assignment_help' => 'عرض الواجبات وتسليمها ومراجعتها.', 'assignment_created' => 'تم إنشاء الواجب بنجاح.', 'assignment_submitted' => 'تم تسليم الواجب بنجاح.', 'feedback_saved' => 'تم حفظ التقييم.', 'all_classes' => 'كل الصفوف', 'general' => 'عام', 'due' => 'الاستحقاق', 'view_assignment' => 'عرض الواجب', 'no_assignments' => 'لا توجد واجبات', 'no_assignments_help' => 'ستظهر الواجبات المنشورة هنا.', 'title' => 'العنوان', 'instructions' => 'التعليمات', 'due_date' => 'تاريخ الاستحقاق', 'publish_assignment' => 'نشر الواجب', 'your_submission' => 'تسليمك', 'submit_assignment' => 'تسليم الواجب', 'submissions' => 'التسليمات', 'marks' => 'الدرجات', 'feedback' => 'التقييم', 'save_feedback' => 'حفظ التقييم', 'no_submissions' => 'لا توجد تسليمات بعد', 'faq' => 'الأسئلة الشائعة', 'all_rights_reserved' => 'جميع الحقوق محفوظة.',
    'login_title' => 'ابدأ معنا', 'login_subtitle' => 'سجل الدخول لبدء الجلسة', 'email_address' => 'البريد الإلكتروني', 'password' => 'كلمة المرور', 'remember_me' => 'تذكرني', 'forgot_password' => 'هل نسيت كلمة المرور؟', 'sign_in' => 'تسجيل الدخول', 'sign_with' => 'تسجيل الدخول عبر', 'no_account' => 'ليس لديك حساب؟', 'sign_up' => 'إنشاء حساب',
];
